name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.7"
      - run: pip install pre-commit
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10.7", "3.11.0-alpha.7" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions/cache@v3
        id: poetry-cache
        with:
          path: ~/.local
          key: ${{ matrix.python-version }}-1
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.1.12
      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-2
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: Run tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest tests
          coverage xml
          coverage report
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
        if: matrix.python-version == '3.10.7'
